<?php require('template/header.phtml') ?>
<div class="container" >
    <div class="tabs-align">
        <ul class="nav nav-tabs">
            <li class="active">
                <a  href="#1" data-toggle="tab">Today</a>
            </li>
            <li>
                <a href="#2" data-toggle="tab">This Week</a>
            </li>
            <li>
                <a href="#3" data-toggle="tab">This Month</a>
            </li>
            <li>
                <a href="#4" data-toggle="tab">This Year</a>
            </li>
        </ul>
    </div>
    <div class="tab-content ">
        <div class="tab-pane active" id="1">
            <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
            <div style="width: 100%; height: 100%" id="chart_divDay"></div>
        </div>
        <div class="tab-pane active" id="2">
            <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
            <div style="width: 100%; height: 100%" id="chart_divWeek"></div>
        </div>
        <div class="tab-pane active" id="3">
            <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
            <div style="width: 100%; height: 100%" id="chart_divMonth"></div>
        </div>
        <div class="tab-pane active" id="4">
            <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
            <div style="width: 100%; height: 100%" id="chart_divYear"></div>
        </div>
    </div>
</div>
<script>
    google.charts.load('current', {packages: ['corechart', 'bar']});
    google.charts.setOnLoadCallback(drawChartDay);
    google.charts.setOnLoadCallback(drawChartWeek);
    google.charts.setOnLoadCallback(drawChartMonth);
    google.charts.setOnLoadCallback(drawChartYear);

    function drawChartDay() {
        var data = google.visualization.arrayToDataTable([
            ['Hours', '<?php echo $view->pageTitle ?> Consumption'],
            <?php
            $view->period='PT1H';
            $view->from='today midnight';
            $view->periodName='Hours';
            $Consum = new ConnectionConsumption($view->type,$view->period, $view->from);
            $consumDataSet = $Consum->getData();
            //            $gasConsum = new ConnectionConsumption('GAS','PT1H', 'today midnight');
            //            $gasDataSet = $gasConsum->getData();
            $view->kwhConsum = $consumDataSet->getConsumptionArray();
            foreach ($view->kwhConsum as $value) {
                echo '[\''.$value->getDate()->modify('-1 hour')->format('H:i').' - '
                    .$value->getDate()->modify('+1 hour')->format('H:i')
                    .'\','.$value->getConsumption().'],
            ';
            }
            ?>
        ]);
        var options = {
            title: '<?php echo $view->pageTitle ?> consumption based on <?php echo $view->periodName ?>',
            chartArea: {width: '55%'},
            isStacked: true,
            height: 600,
            hAxis: {
                title: 'kWh',
                minValue: 0
            },
            vAxis: {
                title: '<?php echo $view->periodName ?>'
            },
            animation: {
                duration: 1000,
                easing: 'out',
                startup: true
            }
        };
        var chart = new google.visualization.BarChart(document.getElementById('chart_divDay'));
        chart.draw(data, options);
    }



    function drawChartWeek() {
        var data = google.visualization.arrayToDataTable([
            ['Hours', '<?php echo $view->pageTitle ?> Consumption'],

            <?php
            $view->period='P1D';
            $view->from='last monday midnight';
            $view->periodName='Days';
            $Consum = new ConnectionConsumption($view->type,$view->period, $view->from);
            $consumDataSet = $Consum->getData();
            $view->kwhConsum = $consumDataSet->getConsumptionArray();
            foreach ($view->kwhConsum as $value) {
                echo '[\''.$value->getDate()->format('D')
                    .'\','.$value->getConsumption().'],
            ';
            }
            ?>
        ]);
        var options = {
            title: '<?php echo $view->pageTitle ?> consumption based on <?php echo $view->periodName ?>',
            chartArea: {width: '55%'},
            isStacked: true,
            height: 600,
            hAxis: {
                title: 'kWh',
                minValue: 0
            },
            vAxis: {
                title: '<?php echo $view->periodName ?>'
            },
            animation: {
                duration: 1000,
                easing: 'out',
                startup: true
            }
        };
        var chart = new google.visualization.BarChart(document.getElementById('chart_divWeek'));
        chart.draw(data, options);
    }



    function drawChartMonth() {
        var data = google.visualization.arrayToDataTable([
            ['Hours', '<?php echo $view->pageTitle ?> Consumption'],

            <?php
            $view->period='P1W';
            $view->from='first day of this month 00:00:00';
            $view->periodName='Weeks';
            $Consum = new ConnectionConsumption($view->type,$view->period, $view->from);
            $consumDataSet = $Consum->getData();
            $view->kwhConsum = $consumDataSet->getConsumptionArray();
            foreach ($view->kwhConsum as $value) {
                echo '[\''.$value->getDate()->format('d-m').' - '
                    .$value->getDate()->modify('+6 days')->format('d-m')
                    .'\','.$value->getConsumption().'],
            ';
            }
            ?>
        ]);
        var options = {
            title: '<?php echo $view->pageTitle ?> consumption based on <?php echo $view->periodName ?>',
            chartArea: {width: '55%'},
            isStacked: true,
            height: 600,
            hAxis: {
                title: 'kWh',
                minValue: 0
            },
            vAxis: {
                title: '<?php echo $view->periodName ?>'
            },
            animation: {
                duration: 1000,
                easing: 'out',
                startup: true
            }
        };
        var chart = new google.visualization.BarChart(document.getElementById('chart_divMonth'));
        chart.draw(data, options);
    }



    function drawChartYear() {
        var data = google.visualization.arrayToDataTable([
            ['Hours', '<?php echo $view->pageTitle ?> Consumption'],

            <?php
            $view->period='P1M';
            $view->from='first day of January 00:00:00';
            $view->periodName='Months';
            $Consum = new ConnectionConsumption($view->type,$view->period, $view->from);
            $consumDataSet = $Consum->getData();
            $view->kwhConsum = $consumDataSet->getConsumptionArray();
            foreach ($view->kwhConsum as $value) {
                echo '[\''.$value->getDate()->format('M')
                    .'\','.$value->getConsumption().'],
            ';
            }
            ?>
        ]);
        var options = {
            title: '<?php echo $view->pageTitle ?> consumption based on <?php echo $view->periodName ?>',
            chartArea: {width: '55%'},
            isStacked: true,
            height: 600,
            hAxis: {
                title: 'kWh',
                minValue: 0
            },
            vAxis: {
                title: '<?php echo $view->periodName ?>'
            },
            animation: {
                duration: 1000,
                easing: 'out',
                startup: true
            }
        };
        var chart = new google.visualization.BarChart(document.getElementById('chart_divYear'));
        chart.draw(data, options);
    }
</script>

<?php require('template/footer.phtml') ?>
