<?php require('template/header.phtml') ?>
<div class="container" >
    <div class="tabs-align">
        <ul class="nav nav-tabs">
            <li class="active">
                <a id="dayTabTop" href="#dayTab" data-toggle="tab">Today</a>
            </li>
            <li>
                <a id="weekTabTop" href="#weekTab" data-toggle="tab">This Week</a>
            </li>
            <li>
                <a id="monthTabTop" href="#monthTab" data-toggle="tab">This Month</a>
            </li>
            <li>
                <a id="yearTabTop" href="#yearTab" data-toggle="tab">This Year</a>
            </li>
        </ul>
    </div>
    <div class="tab-content ">
        <div class="tab-pane active" id="dayTab">
            <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
            <div style="width: 100%; height: 100%" id="chart_divDay"></div>
        </div>
        <div class="tab-pane " id="weekTab">
            <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
            <div style="width: 100%; height: 100%" id="chart_divWeek"></div>
        </div>
        <div class="tab-pane " id="monthTab">
            <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
            <div style="width: 100%; height: 100%" id="chart_divMonth"></div>
        </div>
        <div class="tab-pane " id="yearTab">
            <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
            <div style="width: 100%; height: 100%" id="chart_divYear"></div>
        </div>
    </div>
</div>

<?php require('template/chartScript.phtml') ?>

<?php require('template/footer.phtml') ?>
