<?php require('template/header.phtml') ?>
    <div class="pricingdiv">

        <ul class="theplan">
            <li class="title"><?php if ($view->todayIsBetter == false) { ?><span class="icon-trophy"
                                                                                 style="color:yellow"></span><?php } ?>
                <b>Yesterday</b></li>
            <li><b>Date:</b> <?php echo date('d/m/Y', strtotime("-1 days")); ?></li>
            <li><b>Total Energy Consumption:</b> <?php echo $view->yesterdayConsumption; ?> kwh</li>
            <li><b>Gas Consumption:</b> <?php echo $view->gasYesterday; ?> kwh</li>
            <li><b>Electric Consumption:</b> <?php echo $view->elecYesterday; ?> kwh</li>
        </ul>

        <ul class="theplan">
            <li class="title"><?php if ($view->todayIsBetter) { ?><span class="icon-trophy"
                                                                        style="color:yellow"></span><?php } ?>
                <b>Today</b></li>
            <li><b>Date:</b> <?php echo date('d/m/Y'); ?></li>
            <li><b>Total Energy Consumption:</b> <?php echo $view->todayConsumption; ?> kwh</li>
            <li><b>Gas Consumption:</b> <?php echo $view->gasToday; ?> kwh</li>
            <li><b>Electric Consumption:</b> <?php echo $view->elecToday; ?> kwh</li>
        </ul>

        <ul class="theplan">
            <li class="title"><b>Difference</b></li>
            <li><b>Energy Consumption difference:</b> <?php echo $view->consumptionDifference; ?> kwh</li>
            <li><b>Gas difference:</b> <?php echo $view->gasDifference; ?> kwh</li>
            <li><b>Electric difference:</b> <?php echo $view->electricDifference; ?> kwh</li>
        </ul>
    </div>

    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700">

    <style>
        .pricingdiv {
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
            font-family: 'Source Sans Pro', Arial, sans-serif;
        }

        .pricingdiv ul.theplan {
            list-style: none;
            margin: 0;
            padding: 0;
            border-top-left-radius: 50px;
            border-bottom-right-radius: 50px;
            color: white;
            background: #7c3ac9;
            margin-right: 10px; /* spacing between tables */
            margin-bottom: 1em;
            transition: all .5s;
        }

        .pricingdiv ul.theplan:hover { /* when mouse hover over pricing table */
            transform: scale(1.05);
            transition: all .5s;
            z-index: 100;
            box-shadow: 0 0 10px gray;
        }

        .pricingdiv ul.theplan li {
            margin: 10px 20px;
            position: relative;
        }

        .pricingdiv ul.theplan li.title {
            font-size: 150%;
            font-weight: bold;
            text-align: center;
            margin-top: 20px;
            text-transform: uppercase;
            border-bottom: 5px solid white;
        }

        .pricingdiv ul.theplan:nth-of-type(2) {
            background: #e53499;
        }

        .pricingdiv ul.theplan:nth-of-type(3) {
            background: #2a2cc8;
        }

        .pricingdiv ul.theplan:last-of-type { /* remove right margin in very last table */
            margin-right: 0;
        }

        @media only screen and (max-width: 500px) {
            .pricingdiv ul.theplan {
                border-radius: 0;
                width: 100%;
                margin-right: 0;
            }

            .pricingdiv ul.theplan:hover {
                transform: none;
                box-shadow: none;
            }
        }
    </style>
<?php require('template/footer.phtml') ?>