<?php require('template/header.phtml') ?>
    <div class="container" >
        <div class="tabs-align">
            <ul class="nav nav-tabs">
                <li >
                    <a>Compare With: </a>
                </li>
                <li class="active">
                    <a id="dayTabTop" href="#dayTab" data-toggle="tab">Yesterday</a>
                </li>
                <li>
                    <a id="weekTabTop" href="#weekTab" data-toggle="tab">Last Week</a>
                </li>
                <li>
                    <a id="monthTabTop" href="#monthTab" data-toggle="tab">Last Month</a>
                </li>
                <li>
                    <a id="yearTabTop" href="#yearTab" data-toggle="tab">Last Year</a>
                </li>
            </ul>
        </div>
    <div class="tab-content ">
        <div class="tab-pane active" id="dayTab" style="margin-top: 20px; ">
            <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
            <div style="width: 100%; height: 100%" id="chart_divCompDay"></div>
        </div>
        <div class="tab-pane" id="weekTab" style="margin-top: 20px; ">
            <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
            <div style="width: 100%; height: 100%" id="chart_divCompWeek"></div>
        </div>
        <div class="tab-pane" id="monthTab" style="margin-top: 20px; ">
            <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
            <div style="width: 100%; height: 100%" id="chart_divCompMonth"></div>
        </div>
        <div class="tab-pane" id="yearTab" style="margin-top: 20px; ">
            <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
            <div style="width: 100%; height: 100%" id="chart_divCompYear"></div>
        </div>
    </div>
    </div>

<?php require('template/chartScript.phtml') ?>

<?php require('template/footer.phtml') ?>