<?php require('template/header.phtml') ?>
    <div class="container" >
    <div class="tab-content ">
    <div class="tab-pane active" id="chart">
        <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
        <div style="width: 100%; height: 100%" id="chart_divElecComp"></div>
        <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
        <div style="width: 100%; height: 100%" id="chart_divGasComp"></div>
    </div>
    </div>
    </div>

<?php require('template/chartComparisonScript.phtml') ?>

<?php require('template/footer.phtml') ?>