<?php require('template/header.phtml') ?>

<div class="row justify-content-center">
    <ul class="nav nav-tabs">
        <li class="active">
            <a  href="#1" data-toggle="tab">Current Month</a>
        </li>
        <li><a href="#2" data-toggle="tab">Predicted Cost</a>
        </li>
    </ul>
</div>
    <div class="tab-content ">
        <div class="tab-pane active" id="1">
            <article id="page-iconcolumn" class="page-section">

                <section class="layout-iconcolumns container py-4">

                    <div class="row text-center">

                        <section class="col-md-4 my-3">
    <span class="fa-stack fa-2x">
      <i class="fas fa-circle-notch fa-9x"></i>
    </span>
                            <h4 class="overlay-to-circle"><i class="fas fa-bolt fa-7x"></i></h4>
                            <h3 class="under-circle">£16,54</h3>
                        </section>

                        <section class="col-md-4 my-3">
    <span class="fa-stack fa-2x">
      <i class="fas fa-circle-notch fa-9x"></i>
    </span>
                            <h4 class="overlay-to-circle"><i class="fas fa-fire fa-7x"></i></h4>
                            <h3 class="under-circle">£18,87</h3>
                        </section>



                    </div>

                </section>

            </article>
        </div>
        <div class="tab-pane " id="2">
            <article id="page-iconcolumn" class="page-section">

                <section class="layout-iconcolumns container py-4">

                    <div class="row text-center">

                        <section class="col-md-4 my-3">
    <span class="fa-stack fa-2x">
      <i class="fas fa-circle-notch fa-9x"></i>
    </span>
                            <h4 class="overlay-to-circle"><i class="fas fa-bolt fa-7x"></i></h4>
                            <h3 class="under-circle">£43,54</h3>
                        </section>

                        <section class="col-md-4 my-3">
    <span class="fa-stack fa-2x">
      <i class="fas fa-circle-notch fa-9x"></i>
    </span>
                            <h4 class="overlay-to-circle"><i class="fas fa-fire fa-7x"></i></h4>
                            <h3 class="under-circle">£31,87</h3>
                        </section>



                    </div>

                </section>

            </article>
        </div>
    </div>

<?php require('template/footer.phtml') ?>
