<?php require('template/header.phtml') ?>

<article id="page-iconcolumn" class="page-section">

<section class="layout-iconcolumns container py-4">

  <div class="row text-center">

    <section class="col-md-4 my-3">
    <span class="fa-stack fa-2x">
      <i class="fas fa-circle-notch fa-9x"></i>
    </span>
    <h4 class="overlay-to-circle"><i class="fas fa-bolt fa-5x"></i></h4>
        <h3 class="under-circle">£16,54</h3>
    </section>

    <section class="col-md-4 my-3">
    <span class="fa-stack fa-2x">
      <i class="fas fa-circle-notch fa-9x"></i>
    </span>
        <h4 class="overlay-to-circle"><i class="fas fa-fire fa-5x"></i></h4>
    <h3 class="under-circle">£18,87</h3>
    </section>



  </div>

</section>
<article class="">

</article>

</article>
