<?php require('template/header.phtml') ?>

<form method="post" action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]);?>">
    <div class="container">
        <div class="py-5 text-center">
            <h2>Your budget has been updated</h2>
            <?php if (isset($gasPrice)) echo " Your new  gas budget is : " . $gasPrice . "$" ?>
            <?php if (isset($electricPrice)) echo " <br> " . " Your new electricity budget is : " . $electricPrice . "$" ?>
            <button class="btn btn-primary btn-lg col-sm-12" type="submit" name="return">Return to Home Page</button>
        </div>
    </div>
</form>
<?php require('template/footer.phtml') ?>
