
<script>
    google.charts.load('current', {packages: ['corechart', 'bar']});
    google.charts.setOnLoadCallback(initializePound);
    function initializePound () {
        $('#costTabTop').click(function() {
            setTimeout(
                function() {
                    drawChartPound();
                },
                50)
        });
    }
    google.charts.setOnLoadCallback(initializeKWH);
    function initializeKWH () {
        $('#kwhTabTop').click(function() {
            setTimeout(
                function() {
                    drawChartKWH();
                },
                50)
        });
    }

    function drawChartPound() {
        var data = google.visualization.arrayToDataTable([
            ['Time', 'Electricity Cost Prediction', 'Gas Cost Prediction'],
            <?php
                for ($i=0; $i<sizeof($view->predictedUsageElec); $i++){
                    $view->weatherPredictionSet[$i]->convertToCelcius();
                    echo '[\''.$view->weatherPredictionSet[$i]->getTime()->format('D d'). ' ('
                        .intval($view->weatherPredictionSet[$i]->getTemp()) .'℃)' .'\','
                        .$view->predictedUsageElec[$i]->getPredictedCost('Elec').','
                        .$view->predictedUsageGas[$i]->getPredictedCost('Gas').'],
            ';
                }
            ?>
        ]);
        var periodName = 'Days';
        // set common style for chart
        var options = styleChart(data.getNumberOfRows(), periodName, '£ Pounds', 'Cost');
        var chart = new google.visualization.BarChart(document.getElementById('chart_divCost'));
        chart.draw(data, options);
    }

    function drawChartKWH() {
        var data = google.visualization.arrayToDataTable([
            ['Time', 'Electricity Consumption Prediction', 'Gas Consumption Prediction'],
            <?php
            for ($i=0; $i<sizeof($view->predictedUsageElec); $i++){
                echo '[\''.$view->weatherPredictionSet[$i]->getTime()->format('D d'). ' ('
                    .intval($view->weatherPredictionSet[$i]->getTemp()) . '℃)' .'\','
                    .$view->predictedUsageElec[$i]->getConsumption().','
                    .$view->predictedUsageGas[$i]->getConsumption().'],
            ';
            }
            ?>
        ]);
        var periodName = 'Days';
        // set common style for chart
        var options = styleChart(data.getNumberOfRows(), periodName, 'kWh', 'Consumption');
        var chart = new google.visualization.BarChart(document.getElementById('chart_divKWH'));
        chart.draw(data, options);
    }

    function styleChart(NumberOfRows, periodName, unit, title){
        var chartAreaHeight;
        if (NumberOfRows <= 5){
            // set inner height to 70 pixels per row
            chartAreaHeight = NumberOfRows * 70;
        }
        else if (NumberOfRows <= 12){
            // set inner height to 50 pixels per row
            chartAreaHeight = NumberOfRows * 50;
        }
        else if (NumberOfRows <= 18){
            // set inner height to 50 pixels per row
            chartAreaHeight = NumberOfRows * 30;
        }
        else{
            // set inner height to 30 pixels per row
            chartAreaHeight = NumberOfRows * 20;
        }
        // add padding to outer height to accomodate title, axis labels, etc
        var chartHeight = chartAreaHeight + 150;
        return options = {
            title: title+' Based On Weather Prediction for 5 Days',
            titleTextStyle:{fontSize: 19},
            chartArea: {
                width: '60%',
                height: chartAreaHeight
            },
            //isStacked: true,
            colors: ['#efda00', '#8e48b0'],
            height: chartHeight,
            hAxis: {
                title: unit,
                minValue: 0,
                maxValue: 0.1,
                viewWindow: {
                    min:0},
                titleTextStyle:{fontSize: 17},
                textStyle:{fontSize: 17}
            },
            vAxis: {
                title: periodName,
                titleTextStyle:{fontSize: 17},
                textStyle:{fontSize: 17},
                // textPosition: 'in'
            },
            legend: {textStyle:{fontSize: 17}},
            tooltip: {textStyle:{fontSize: 17}},
            animation: {
                duration: 1000,
                easing: 'out',
                startup: true
            }
        };
    }
</script>