</div>
</div>
</div>
<!-- /#page-content-wrapper -->


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="js/jquery-migrate-3.0.1.min.js"></script>
<script src="js/jquery.easing.1.3.js"></script>
<script src="js/jquery.stellar.min.js"></script>
<script src="js/aos.js"></script>
<script src="js/scrollax.min.js"></script>
<script src="js/main.js"></script>

<script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
</script>

<!--<script>-->
<!--    //script that assure that all charts are loaded with the window width-->
<!--    function activeElement() {-->
<!--        document.getElementById("emptySpaceTab").className = "tab-pane";-->
<!--        document.getElementById("weekTab").className = "tab-pane";-->
<!--        document.getElementById("monthTab").className = "tab-pane";-->
<!--        document.getElementById("yearTab").className = "tab-pane";-->
<!--    }-->
<!--    setTimeout(activeElement, 1000);-->
<!--</script>-->

<script>
    $( document ).ready(function() {
        $( "#doughnut" ).click(function() {
            setTimeout(
                function() {
                    chartContainerElec('chartContainer','Electricity',<?php echo $view->totalElec ?>,40)
                },
                50);
            setTimeout(
                function() {
                        chartContainerGas('chartContainer2','Gas',<?php echo $view->totalGas ?>,40)
                },
                50);
        });
    });

    function chartContainerElec ( target,type,Cost,setBadget) {
        var remainingBudget = setBadget-Cost;
        CanvasJS.addColorSet("set",
            [//colorSet Array
                <?php echo "\"" . $colour[0] . "\""; ?>
                ,"lightgrey"
            ]);
        var chart = new CanvasJS.Chart(target,
            {
                colorSet: "set",

                exportEnabled: true,
                animationEnabled: true,
                title:{
                    text: type+" Monthly Cost "
                },
                legend:{
                    cursor: "pointer",
                    itemclick: explodePie
                },
                data: [{
                    type: "doughnut",
                    showInLegend: true,
                    toolTipContent: "{name}: <strong>£{y}</strong>",
                    indexLabel: "{name} - £{y}",
                    dataPoints: [
                        { y: Cost, name: "Current " +type +" Cost", exploded: true },
                        { y: remainingBudget, name: "Remaining  Budget" },

                    ]
                }]
            });
        chart.render();

    };

    function chartContainerGas ( target,type,Cost,setBadget) {
        var remainingBudget = setBadget-Cost;
        CanvasJS.addColorSet("set",
            [//colorSet Array
                <?php echo "\"" . $colour[1] . "\""; ?>
                ,"lightgrey"
            ]);
        var chart = new CanvasJS.Chart(target,
            {
                colorSet: "set",

                exportEnabled: true,
                animationEnabled: true,
                title:{
                    text: type+" Monthly Cost "
                },
                legend:{
                    cursor: "pointer",
                    itemclick: explodePie
                },
                data: [{
                    type: "doughnut",
                    showInLegend: true,
                    toolTipContent: "{name}: <strong>£{y}</strong>",
                    indexLabel: "{name} - £{y}",
                    dataPoints: [
                        { y: Cost, name: "Current " +type +" Cost", exploded: true },
                        { y: remainingBudget, name: "Remaining  Budget" },

                    ]
                }]
            });
        chart.render();

    };

    function explodePie (e) {
        if(typeof (e.dataSeries.dataPoints[e.dataPointIndex].exploded) === "undefined" || !e.dataSeries.dataPoints[e.dataPointIndex].exploded) {
            e.dataSeries.dataPoints[e.dataPointIndex].exploded = true;
        } else {
            e.dataSeries.dataPoints[e.dataPointIndex].exploded = false;
        }
        e.chart.render();

    }
</script>

</body>
</html>
